#include<bits/stdc++.h>

using namespace std;

int drugCnt = 40, streetCnt = 37, DosageFormCnt = 5;

string drugsName[161] = {
"Adara's Rose",
"Adravil",
"Alprazaline",
"ALZ-112, ALZ-113",
"Ambrosia",
"Axelavier",
"Anabiotics",
"Anti-Ague",
"Antibiotic Gel (AKA Heal Jelly)",
"Antidote",
"Athsat",
"Aqua Cure",
"Aquasol",
"Batika Indica",
"Bio-mimetic gel",
"Bittamucin",
"Blaccine",
"Biofoam",
"Byphodine",
"Cancer dust",
"Caring",
"Carabonal",
"Catana",
"Celestial Wine",
"Chamalla extract",
"Charlanta",
"Chiquitolina, pastillas de",
"Cloveritol",
"Comanapracil",
"Cortexiphan",
"Counteragent",
"Cryostim",
"Damascus Rose (Amnesia potion)",
"Daylight",
"DC2",
"Dehalcynate",
"Dioxnyl",
"Doloxan",
"Digitalin",
"Dragon Sand",
"Dreamy Sleepy Nighty Snoozy Snooze",
"Dried Frog Pills",
"Dylar",
"Dypraxa",
"Elixir of life",
"Elixir of Long Life",
"Elyon's Water",
"Estus",
"Ether",
"Expectane",
"Fast-penta",
"Felicium",
"Flora-Flor",
"Flintstones Chewable Morphine",
"Flu Buddy",
"Focusyn",
"Formula 977",
"Fukitol",
"Gambutrol",
"Gels",
"Heal(ing) potion",
"Hibernol",
"Hourai Elixir",
"Hydra",
"Hydromel",
"Hydronium Bromide",
"Hydroxl",
"Hypnocil",
"Hyronalin",
"Imobatine",
"Inaprovaline",
"Interfectum",
"Isoprovalyn",
"Jamitol",
"Jammitin",
"Jet Antidote",
"JJ-180",
"Kallocain",
"Kalocin",
"Krayoxx",
"Lethe",
"Lithium dibromide",
"Lot 6",
"Masiform D",
"Med-X",
"Medicinal Compound",
"Medi-Gel",
"Mem",
"Mephisto",
"Metazine",
"Miracurall",
"Miseth",
"Monomate, Dimate, and Trimate",
"Morpha",
"Morphling",
"Nappien",
"Necrotech Serum",
"Nectar",
"Neodextraline solution",
"Neuropozyne",
"Nexus",
"Nine Flower Jade Dew Pill",
"Nomolestol",
"Novril",
"Nyquil Cold, Flu & AIDS",
"Oret",
"Panexa",
"Pasceline D",
"Phalanx",
"Phalanxifor",
"Phoenix Down",
"Phoenix Tears",
"Placiden",
"Plasmids",
"Plomox",
"Pressure Pill",
"Prexilin",
"Procrastin-X (phenalazidine slackahide)",
"Progenitorivox",
"Provasic (RDU-90)",
"Provolanaproxalidamine C",
"PX-41 Antidote",
"Pylene-50",
"Qualex",
"RadAway",
"Rad-X",
"Recolada virus",
"Relaxabrex",
"Repressitol",
"Retinax 5",
"Ritalout",
"Ryetalyn",
"Ryll",
"Semuta",
"Senzu Bean",
"Selenine",
"Serisone",
"Serum 114",
"Shinten",
"Skele-gro",
"Soft Green Echo Eyedrop Antidote",
"Soma",
"Sopor slime",
"Space Mead",
"Spectrox",
"Stabilliser",
"Starshade",
"Stim pack",
"Stim-pak",
"Sym-Bac",
"Telol",
"Tribonin",
"Triopenin",
"Turbolax",
"Tunivor's Nectar",
"Varatril",
"Vigors",
"Viopril",
"Xorax",
"Zombrex",
"Zydrate"
};


string streetName[38] = {
"Acanthia Way",
"Alleyway between Magnolia Crescent and Wisteria Walk",
"Bermondsey Wall",
"Charing Cross Road",
"Chislehurst Gardens",
"Church Lane",
"Downing Street",
"Drury Lane",
"Ephraim Lane",
"Erdbergstrasse",
"Grangers' Home: Heathgate, Hampstead",
"Grimmauld Place",
"High Street (Godric's Hollow)",
"High Street (Hogsmeade)",
"Horizont Alley",
"Laburnum Gardens",
"Lanes End",
"Magnolia Crescent",
"Magnolia Road",
"Make Street",
"North Street",
"Orchard Street",
"Pike Street",
"Privet Drive",
"Pudding Lane",
"Rose Street",
"Scotland Place",
"Shaftesbury Avenue",
"South Way",
"Spinner's End",
"Tollington Way",
"Tottenham Court Road",
"Vauxhall Road",
"Victoria Embankment",
"West 24th Street",
"Whitehall",
"Wildbrook Crescent",
"Wisteria Walk"
};


string componentName[48] = {
"aqua pura",
"Aconite (Wolfsbane)",
"Acromantula venom",
"Adder's Fork",
"Agrippa",
"Angel's Trumpet",
"Antimony",
"Armadillo bile",
"Ashwinder egg",
"Asphodel",
"Baneberry",
"Bat blood",
"Bat spleen",
"Belladonna",
"Bezoar",
"Bicorn horn",
"Billywig sting",
"Billywig sting slime",
"Black beetle eye",
"Blind-worm's Sting",
"Blood",
"Boom Berry",
"Boomslang",
"Boomslang skin",
"Bouncing Spider Juice",
"Bubotuber pus",
"Bulbadox juice",
"Butterscotch",
"Cat hair",
"Caterpillar",
"Chinese Chomping Cabbage",
"Chizpurfle carapace",
"Cinnamon",
"Cockroach",
"Croakoa",
"Crocodile heart",
"Daisy",
"Dandelion root",
"Deadlyius",
"Death-Cap",
"Dittany",
"Doxy egg",
"Dragon blood",
"Dragon claw",
"Dragon dung",
"Dragon horn",
"Dragon liver",
"Dragonfly thorax"
};

string DosageFormName[11] = {
"tablet", 
"capsule", 
"syrops", 
"suspension", 
"syrup", 
"powder", 
"liquid", 
"solid crystals", 
"natural or herbal plant", 
"seed", 
"pastes"
};

void genDosageForm() {
    random_shuffle(DosageFormName, DosageFormName + 11);
    printf("INSERT INTO DosageForm(id, name) VALUES\n");
    for (int i = 0; i < DosageFormCnt; ++i) {
        printf("    (%d, '%s')", i, DosageFormName[i].c_str());
        if (i + 1 < DosageFormCnt) {
            printf(",\n");
        } else {
            printf(";\n\n");
        }
    }
}


int main() {
    freopen("inserts.sql", "w", stdout);
    srand(179);
    genDosageForm();
}
